#!/usr/bin/env bash

# Function to display usage instructions
function show_usage {
    echo "Usage: [--video | --picture] <url>"
    echo "  --video: Downloads only videos"
    echo "  --picture: Downloads only pictures"
    echo "  <url>:   The link to download"
    exit 1
}

# Check for the presence of the "--video" or "--pictures" flag
if [ "$1" == "--video" ]; then
    shift  # Remove the flag from arguments
    gallery-dl --filter "extension in ('mp4', 'm4v', 'webm')" "$@"
elif [ "$1" == "--picture" ]; then
    shift  # Remove the flag from arguments
    gallery-dl --filter "extension in ('jpg', 'jpeg', 'png', 'gif', 'webp')" "$@"
elif [ $# -eq 1 ]; then
    gallery-dl "$1"
else
    show_usage
fi
