#!/bin/env bash

# Function to display script usage
usage() {
  echo "Usage: $0 [-f] [-t] [-a] [file]"
  echo "Converts to and from WebP and AVIF."
  echo "  -f  Convert from WebP to JPEG."
  echo "  -t  Convert to WebP from JPEG, PNG, or WebP."
  echo "  -a  Convert from AVIF to JPEG."
  echo "  file  Optional: Path to a single file to convert."
  exit 1
}

# Initialize flags
convert_from_webp=false
convert_to_webp=false
convert_from_avif=false

# Process command line options
while getopts ":ft:a" opt; do
  case ${opt} in
    f)
      convert_from_webp=true
      ;;
    t)
      convert_to_webp=true
      ;;
    a)
      convert_from_avif=true
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      usage
      ;;
  esac
done

# Shift remaining arguments to get the file path, if any
shift $((OPTIND-1))
file="$1"

# Ensure at least one conversion option is specified
if ! $convert_from_webp && ! $convert_to_webp && ! $convert_from_avif; then
  echo "Error: Please specify at least one conversion option (-f, -t, or -a)" >&2
  usage
fi

# Convert files to WebP
if $convert_to_webp; then
  if [[ -n "$file" ]]; then
    cwebp -q 80 "$file" -o "${file%.*}.webp"
  else
    for file in *.jpg *.jpeg *.png *.webp; do
      cwebp -q 80 "$file" -o "${file%.*}.webp"
    done
  fi
fi

# Convert files from WebP
if $convert_from_webp; then
  if [[ -n "$file" ]]; then
    dwebp "$file" -o "${file%.*}.jpg" && rm "$file"  # Output as JPEG and delete WebP
  else
    for file in *.webp; do
      if dwebp "$file" -o "${file%.*}.jpg"; then  # Convert and check for success
        rm "$file"  # Delete WebP if conversion successful
      fi
    done
  fi
fi

# Convert files from AVIF
if $convert_from_avif; then
  for file in *.avif; do
    if [ -f "$file" ]; then
      convert "$file" "${file%.*}.jpg"
      rm "$file"
    fi
  done
fi