#!/usr/bin/env bash

# Function to display script usage
usage() {
    echo "Usage: $0 [-f] [-t]"
    echo "Converts files between webp and jpg, png, heic, avif formats."
    echo "  -f  Convert from webp to jpg."
    echo "  -t  Convert to webp from jpg, png, heic, avif."
    exit 1
}

# Initialize flags
convert_from_webp=false
convert_to_webp=false

# Process command line options
while getopts ":ft" opt; do
    case ${opt} in
        f)
            convert_from_webp=true
            ;;
        t)
            convert_to_webp=true
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            usage
            ;;
    esac
done

# Shift to get the remaining arguments
shift $((OPTIND - 1))

# Check if both flags are provided
if $convert_from_webp && $convert_to_webp; then
    echo "Error: Both -f and -t flags cannot be used together. Use -h for help."
    exit 1
fi

# Convert from webp to jpg
if $convert_from_webp; then
    for file in *.webp; do
        dwebp ./"$file" -o ./"${file%.webp}.jpg"
    done
fi

# Convert to webp from jpg, png, heic, avif
if $convert_to_webp; then
    for file in *.{jpg,png,heic,avif}; do
        case "${file##*.}" in
            jpg | png | heic | avif)
                cwebp -q 80 ./"$file" -o ./"${file%.*}.webp"
                ;;
            *)
                echo "Skipping $file, unsupported format."
                ;;
        esac
    done
fi