#! /bin/sh

if test -z "$sysconfdir"; then
    if test -n "$etc"; then
        sysconfdir=$etc
    else
        sysconfdir=$prefix/etc
    fi
fi

if test -z "$1"; then
    echo "Usage: $0 <service>"
    exit 1
fi

if test -r $sysconfdir/pam.d/$1 || grep "^$1" $sysconfdir/pam.conf >/dev/null 2>&1; then
    echo "PAM service \"$1\" already configured."
    exit 0
fi

if test -d $sysconfdir/pam.d; then
    if test ! -w $sysconfdir/pam.d; then
	echo "Error: need write access to $sysconfdir/pam.d/ to install PAM service definition!"
	exit 1
    fi
    for sv in kde login; do
	if test -r $sysconfdir/pam.d/$sv; then
	    echo "Copying PAM service definition file \"$sv\" to \"$1\"."
	    cp $sysconfdir/pam.d/"$sv" $sysconfdir/pam.d/$1
	    exit 0
	fi
    done
    echo "No template PAM service file for \"$1\" found!"
    exit 1
elif test -f $sysconfdir/pam.conf; then
    if test ! -w $sysconfdir/pam.conf; then
	echo "Error: need write access to $sysconfdir/pam.conf to install PAM service definition!"
	exit 1
    fi
    for sv in kde login; do
	serv=`grep "^$sv[ 	]" $sysconfdir/pam.conf`
	if test -n "$serv"; then
	    echo "Copying service definition entry \"$sv\" to \"$1\"."
	    echo >>$sysconfdir/pam.conf
	    echo "$serv" | sed -e "s/^$sv\\([ 	]\\)/$1\\1/" >>$sysconfdir/pam.conf
	    exit 0
	fi
    done
    echo "No template PAM service entry for \"$1\" found!"
    exit 1
else
    echo "Error: don't know where to store the PAM service definition for \"$1\"!"
    exit 1
fi
