#!/usr/bin/env bash
# Grabs the name of the current active window....
# Useful for displaying in conky or genmon....

ps -e | grep $(xdotool getwindowpid $(xdotool getwindowfocus)) | grep -v grep | awk '{print $4}'
