TEMPLATE	= app
CONFIG		+= qt dll release
HEADERS		= 
SOURCES		= trivial.cpp
unix:LIBS	= -lqnp -lXt
win32:LIBS	= $(QTDIR)/lib/qnp.lib
DEF_FILE	= trivial.def
RC_FILE		= trivial.rc
TARGET      	= trivial
win32:TARGET	= nptrivial
