TEMPLATE	= app
CONFIG		+= qt console warn_on release
HEADERS		= uic.h ../shared/widgetdatabase.h ../shared/domtool.h ../integration/kdevelop/kdewidgets.h
SOURCES		= uic.cpp ../shared/widgetdatabase.cpp ../shared/domtool.cpp ../integration/kdevelop/kdewidgets.cpp
TARGET		= uic
INCLUDEPATH	= ../shared ../util ../../../src/3rdparty/zlib/
unix:LIBS	+= -L$(QTDIR)/lib -lqutil -L../lib
win32:LIBS	+= $(QTDIR)/lib/qutil.lib
DEFINES 	+= UIC
DESTDIR		= $(QTDIR)/bin
